/// Výchozí metriky pro režim `pchealth` (mapování na okraje pásku).
List<Map<String, dynamic>> builtinPcHealthMetrics() => [
      {
        'enabled': true,
        'name': 'CPU',
        'type': 'system',
        'metric': 'cpu_usage',
        'min_value': 0,
        'max_value': 100,
        'color_scale': 'blue_green_red',
        'brightness_mode': 'dynamic',
        'brightness_min': 50,
        'brightness_max': 255,
        'zones': ['left'],
      },
      {
        'enabled': true,
        'name': 'RAM',
        'type': 'system',
        'metric': 'ram_usage',
        'min_value': 0,
        'max_value': 100,
        'color_scale': 'cool_warm',
        'brightness_mode': 'dynamic',
        'brightness_min': 50,
        'brightness_max': 255,
        'zones': ['right'],
      },
      {
        'enabled': true,
        'name': 'Teplota CPU',
        'type': 'system',
        'metric': 'cpu_temp',
        'min_value': 35,
        'max_value': 95,
        'color_scale': 'blue_green_red',
        'brightness_mode': 'dynamic',
        'brightness_min': 40,
        'brightness_max': 255,
        'zones': ['top'],
      },
      {
        'enabled': true,
        'name': 'Disk',
        'type': 'system',
        'metric': 'disk_usage',
        'min_value': 0,
        'max_value': 100,
        'color_scale': 'cyan_yellow',
        'brightness_mode': 'dynamic',
        'brightness_min': 40,
        'brightness_max': 255,
        'zones': ['bottom'],
      },
    ];
